-- Hoja de Ruta - deploy DEV. Ejecutar UN bloque a la vez, en el orden listado.
-- Cada bloque termina con GO. Los SP se obtienen sin cambios lÃ³gicos desde StoredProcedures.

--REVISAR QUE LOS SOCIOS Y REVISORES DE PRUEBA TENGAN SECTOR Y SEAN MANUALES

-- Agregar campo entra_object_id a revisores
ALTER TABLE REVISORES ADD entra_object_id UNIQUEIDENTIFIER NULL
GO

-- Modificar columna Result de SyncControl
--NO REALIZAR, CHEQUEAR EN LA BD SI ESTA COMO MAX CON sp_help 'SyncControl';
--ALTER TABLE SyncControl ALTER COLUMN Result nvarchar(256);
--GO

-- Agregar columna a Clientes_Creatio
IF COL_LENGTH('dbo.Clientes_Creatio', 'Hdr_Activo') IS NULL ALTER TABLE dbo.Clientes_Creatio ADD Hdr_Activo bit NOT NULL CONSTRAINT DF_Clientes_Creatio_Hdr_Activo DEFAULT (1) WITH VALUES;
GO

-- Agregar columnas a revisores y socios
IF COL_LENGTH('dbo.SOCIOS', 'Hdr_Activo') IS NULL ALTER TABLE dbo.SOCIOS ADD Hdr_Activo bit NOT NULL CONSTRAINT DF_SOCIOS_Hdr_Activo DEFAULT (1) WITH VALUES; IF COL_LENGTH('dbo.REVISORES', 'Hdr_Activo') IS NULL ALTER TABLE dbo.REVISORES ADD Hdr_Activo bit NOT NULL CONSTRAINT DF_REVISORES_Hdr_Activo DEFAULT (1) WITH VALUES;
GO

-- Agregar entra_object_id a socios y revisores
IF COL_LENGTH('dbo.SOCIOS', 'entra_object_id') IS NULL ALTER TABLE dbo.SOCIOS ADD entra_object_id NVARCHAR(100) NULL; IF COL_LENGTH('dbo.REVISORES', 'entra_object_id') IS NULL ALTER TABLE dbo.REVISORES ADD entra_object_id NVARCHAR(100) NULL;
GO

-- Agregar columna a sectores
IF COL_LENGTH('dbo.SECTORES', 'Hdr_Activo') IS NULL ALTER TABLE dbo.SECTORES ADD Hdr_Activo bit NOT NULL CONSTRAINT DF_SECTORES_Hdr_Activo DEFAULT (1) WITH VALUES;
GO

-- Crear tipo HDR_DirectoryUserIdentity
IF TYPE_ID(N'dbo.HDR_DirectoryUserIdentity') IS NULL EXEC(N'CREATE TYPE dbo.HDR_DirectoryUserIdentity AS TABLE (EntraObjectId NVARCHAR(100) NULL, Mail NVARCHAR(150) NULL)');
GO

-- Crear tipo HDR_DirectoryReconciliationIdentity
IF TYPE_ID(N'dbo.HDR_DirectoryReconciliationIdentity') IS NULL EXEC(N'CREATE TYPE dbo.HDR_DirectoryReconciliationIdentity AS TABLE (EntraObjectId NVARCHAR(100) NULL, Mail NVARCHAR(150) NULL, AllowMailFallback BIT NOT NULL)');
GO

-- Nueva tabla de errores
IF OBJECT_ID(N'dbo.ErrorLog', N'U') IS NULL BEGIN CREATE TABLE dbo.ErrorLog ( Id bigint IDENTITY(1,1) NOT NULL, IncidentId varchar(12) NOT NULL, OccurredAt datetime2(3) NOT NULL, ErrorCode varchar(80) NOT NULL, UserName nvarchar(256) NULL, HojaId nvarchar(128) NULL, OperationId varchar(64) NULL, Endpoint nvarchar(512) NOT NULL, UserMessage nvarchar(500) NOT NULL, ExceptionMessage nvarchar(4000) NOT NULL, CONSTRAINT PK_ErrorLog PRIMARY KEY CLUSTERED (Id), CONSTRAINT UX_ErrorLog_IncidentId UNIQUE (IncidentId) ); CREATE INDEX IX_ErrorLog_OccurredAt ON dbo.ErrorLog (OccurredAt); CREATE INDEX IX_ErrorLog_HojaId ON dbo.ErrorLog (HojaId); CREATE INDEX IX_ErrorLog_OperationId ON dbo.ErrorLog (OperationId); CREATE INDEX IX_ErrorLog_ErrorCode ON dbo.ErrorLog (ErrorCode); END
GO

IF COL_LENGTH(N'dbo.ErrorLog', N'Fingerprint') IS NULL ALTER TABLE dbo.ErrorLog ADD Fingerprint varchar(64) NULL;
IF COL_LENGTH(N'dbo.ErrorLog', N'ResolvedAt') IS NULL ALTER TABLE dbo.ErrorLog ADD ResolvedAt datetime2(3) NULL;
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET QUOTED_IDENTIFIER ON; SET NUMERIC_ROUNDABORT OFF; IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ErrorLog') AND name = N'UX_ErrorLog_Fingerprint_Open') BEGIN CREATE UNIQUE INDEX UX_ErrorLog_Fingerprint_Open ON dbo.ErrorLog (Fingerprint) WHERE Fingerprint IS NOT NULL AND ResolvedAt IS NULL; END;


-- HOJAS verificar preparo_fecha
SELECT preparo_fecha,numeracion FROM hojas WHERE TRY_CONVERT(date, preparo_fecha, 103) IS NULL;
GO

-- HOJAS agregar columna temporal
ALTER TABLE hojas ADD FechaDate date;
GO

-- HOJAS actualizar columna temporal
UPDATE hojas SET FechaDate = TRY_CONVERT(date, preparo_fecha, 103)
GO

-- HOJAS reemplazar preparo_fecha
ALTER TABLE hojas DROP COLUMN preparo_fecha; EXEC sp_rename 'hojas.FechaDate', 'preparo_fecha', 'COLUMN';
GO

-- SOCIOS agregar sector
ALTER TABLE dbo.SOCIOS ADD sector NVARCHAR(50) NULL;
GO

-- SOCIOS completar sector desde revisores
UPDATE socio SET sector = revisor.Area FROM dbo.SOCIOS AS socio OUTER APPLY ( SELECT TOP (1) r.area FROM dbo.REVISORES AS r WHERE NULLIF(r.area, '') IS NOT NULL AND ( (NULLIF(socio.entra_object_id, '') IS NOT NULL AND socio.entra_object_id = r.entra_object_id) OR (NULLIF(socio.entra_object_id, '') IS NULL AND socio.mail = r.mail) ) ORDER BY r.area ) AS revisor WHERE NULLIF(socio.sector, '') IS NULL AND NULLIF(revisor.area, '') IS NOT NULL;
GO

--HojaNumerador (solo en dev)
IF OBJECT_ID(N'dbo.HojaNumerador', N'U') IS NULL BEGIN CREATE TABLE dbo.HojaNumerador (Nombre varchar(50) NOT NULL CONSTRAINT PK_HojaNumerador PRIMARY KEY, UltimoNumero int NOT NULL); END; IF NOT EXISTS (SELECT 1 FROM dbo.HojaNumerador WHERE Nombre = 'HOJAS') BEGIN INSERT INTO dbo.HojaNumerador (Nombre, UltimoNumero) SELECT 'HOJAS', ISNULL(MAX(TRY_CONVERT(int, numeracion)), 0) FROM dbo.hojas; END ELSE BEGIN UPDATE dbo.HojaNumerador SET UltimoNumero = (SELECT ISNULL(MAX(TRY_CONVERT(int, numeracion)), 0) FROM dbo.hojas) WHERE Nombre = 'HOJAS' AND UltimoNumero < (SELECT ISNULL(MAX(TRY_CONVERT(int, numeracion)), 0) FROM dbo.hojas); END;

-- SP sp_get_hojas_index_paged.sql
CREATE or ALTER PROCEDURE dbo.sp_get_hojas_index_paged @Nivel INT, @Sector NVARCHAR(50), @Sectores NVARCHAR(MAX) = NULL, @Usuario NVARCHAR(100), @Pendientes BIT, @Numero NVARCHAR(50) = NULL, @Cliente NVARCHAR(255) = NULL, @Estado INT = NULL, @SectorFiltro NVARCHAR(50) = NULL, @Socio NVARCHAR(255) = NULL, @FechaDesde DATE = NULL, @FechaHasta DATE = NULL, @SortField NVARCHAR(50) = N'Numero', @SortDirection NVARCHAR(4) = N'asc', @PageNumber INT = 1, @PageSize INT = 10 AS BEGIN SET NOCOUNT ON; DECLARE @PendientesInt INT; IF (@PageNumber < 1) SET @PageNumber = 1; IF (@PageSize < 1) SET @PageSize = 10; SET @PendientesInt = CASE WHEN @Pendientes = 1 THEN 1 ELSE 0 END; IF OBJECT_ID('tempdb..#BaseHojas') IS NOT NULL DROP TABLE #BaseHojas; CREATE TABLE #BaseHojas ( id NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, usuario NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, equipo NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, cliente INT NULL, sector NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, subarea NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, numeracion NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, descripcion NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, socio_firmante NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, sindica NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, contrato NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, preparo NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, reviso NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, revisogte NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, revisosocio NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, rutapapeles NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, rutadoc NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, observaciones NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, preparo_fecha DATE NULL, reviso_fecha NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, revisogte_fecha NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, revisosocio_fecha NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, fecha_modif NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, hora_modif NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, estado INT NULL, mailasociado NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, generico NVARCHAR(MAX) COLLATE DATABASE_DEFAULT
NULL, revisoengagement NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, nivel_doc INT NULL, manejador NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, fecha_limite NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, lugar_firma NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, manejador_final NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, revisoengagement_fecha NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, Fecha DATE NULL, fecha_cierre DATE NULL, adjuntos NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, archivo_temp NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, archivo_hash NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL, ClienteName NVARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL ); INSERT INTO #BaseHojas EXEC dbo.sp_get_hojas_by_nivel_base @Nivel = @Nivel, @Sector = @Sector, @Sectores = @Sectores, @Usuario = @Usuario, @Id = NULL, @Pendientes = @PendientesInt; WITH SociosUnicos AS ( SELECT mail COLLATE DATABASE_DEFAULT AS mail, MIN(Detalle) AS Detalle FROM dbo.SOCIOS GROUP BY mail ), Base AS ( SELECT h.id AS Id, h.cliente AS Cliente, h.ClienteName, h.sector AS Sector, h.subarea AS Subarea, h.numeracion AS Numero, h.generico AS NombreGenerico, h.descripcion AS Descripcion, h.preparo_fecha AS FechaDocumento, h.revisosocio AS SocioFirmante, sf.Detalle AS SocioFirmanteDetalle, h.sindica AS Sindico, h.contrato AS ContratoPlataforma, h.preparo AS Preparo, h.preparo_fecha AS PreparoFecha, h.reviso AS Reviso, h.reviso_fecha AS RevisoFecha, h.revisogte AS RevisionGerente, h.revisogte_fecha AS RevisionGerenteFecha, h.revisoengagement AS EngagementPartner, h.revisoengagement_fecha AS EngagementPartnerFecha, h.revisosocio_fecha AS SocioFirmanteFecha, h.fecha_limite AS FechaLimite, h.fecha_cierre AS FechaDeCierre, h.manejador_final AS GestorFinal, h.manejador AS Manejador, h.lugar_firma AS LugarFirma, h.rutadoc AS RutaDoc, h.rutapapeles AS RutaPapeles, h.adjuntos AS Adjuntos, h.archivo_temp AS ArchivoTemp, h.archivo_hash AS ArchivoHash, h.observaciones AS Observaciones, h.estado AS Estado FROM #BaseHojas h LEFT JOIN SociosUnicos sf ON sf.mail = h.revisosocio COLLATE DATABASE_DEFAULT WHERE (@Numero IS NULL OR h.numeracion LIKE '%' + @Numero + '%') AND (@Cliente
IS NULL OR h.ClienteName LIKE '%' + @Cliente + '%') AND (@Estado IS NULL OR h.estado = @Estado) AND (@SectorFiltro IS NULL OR h.sector LIKE '%' + @SectorFiltro + '%') AND (@Socio IS NULL OR sf.Detalle LIKE '%' + @Socio + '%') AND (@FechaDesde IS NULL OR h.preparo_fecha >= @FechaDesde) AND (@FechaHasta IS NULL OR h.preparo_fecha <= @FechaHasta) ), Ordered AS ( SELECT *, COUNT(1) OVER() AS TotalItems, ROW_NUMBER() OVER ( ORDER BY CASE WHEN @SortField = N'Numero' AND @SortDirection = N'asc' THEN Numero END ASC, CASE WHEN @SortField = N'Numero' AND @SortDirection = N'desc' THEN Numero END DESC, CASE WHEN @SortField = N'ClienteName' AND @SortDirection = N'asc' THEN ClienteName END ASC, CASE WHEN @SortField = N'ClienteName' AND @SortDirection = N'desc' THEN ClienteName END DESC, CASE WHEN @SortField = N'NombreGenerico' AND @SortDirection = N'asc' THEN NombreGenerico END ASC, CASE WHEN @SortField = N'NombreGenerico' AND @SortDirection = N'desc' THEN NombreGenerico END DESC, CASE WHEN @SortField = N'Sector' AND @SortDirection = N'asc' THEN Sector END ASC, CASE WHEN @SortField = N'Sector' AND @SortDirection = N'desc' THEN Sector END DESC, CASE WHEN @SortField = N'SocioFirmanteDetalle' AND @SortDirection = N'asc' THEN SocioFirmanteDetalle END ASC, CASE WHEN @SortField = N'SocioFirmanteDetalle' AND @SortDirection = N'desc' THEN SocioFirmanteDetalle END DESC, CASE WHEN @SortField = N'FechaDocumento' AND @SortDirection = N'asc' THEN FechaDocumento END ASC, CASE WHEN @SortField = N'FechaDocumento' AND @SortDirection = N'desc' THEN FechaDocumento END DESC, CASE WHEN @SortField = N'Estado' AND @SortDirection = N'asc' THEN Estado END ASC, CASE WHEN @SortField = N'Estado' AND @SortDirection = N'desc' THEN Estado END DESC, Numero ASC ) AS RowNumber FROM Base ) SELECT Id, Cliente, ClienteName, Sector, Subarea, Numero, NombreGenerico, Descripcion, FechaDocumento, SocioFirmante, SocioFirmanteDetalle, Sindico, ContratoPlataforma, Preparo, PreparoFecha, Reviso, RevisoFecha, RevisionGerente, RevisionGerenteFecha, EngagementPartner, EngagementPartnerFecha, SocioFirmanteFecha, FechaLimite, FechaDeCierre, GestorFinal, Manejador, LugarFirma,
RutaDoc, RutaPapeles, Adjuntos, ArchivoTemp, ArchivoHash, Observaciones, Estado, TotalItems, @PageNumber AS PageNumber, @PageSize AS PageSize FROM Ordered WHERE RowNumber BETWEEN ((@PageNumber - 1) * @PageSize) + 1 AND (@PageNumber * @PageSize) ORDER BY RowNumber; END;
GO

-- SP sp_get_hojas_by_nivel.sql
CREATE OR ALTER PROCEDURE dbo.sp_get_hojas_by_nivel @Nivel INT, @Sector NVARCHAR(50), @Sectores NVARCHAR(MAX) = NULL, @Usuario NVARCHAR(255), @Id NVARCHAR(50) = NULL, @Pendientes INT = 0 AS BEGIN SET NOCOUNT ON; CREATE TABLE #r ( id NVARCHAR(MAX) NULL, usuario NVARCHAR(MAX) NULL, equipo NVARCHAR(MAX) NULL, cliente INT NULL, sector NVARCHAR(MAX) NULL, subarea NVARCHAR(MAX) NULL, numeracion NVARCHAR(MAX) NULL, descripcion NVARCHAR(MAX) NULL, socio_firmante NVARCHAR(MAX) NULL, sindica NVARCHAR(MAX) NULL, contrato NVARCHAR(MAX) NULL, preparo NVARCHAR(MAX) NULL, reviso NVARCHAR(MAX) NULL, revisogte NVARCHAR(MAX) NULL, revisosocio NVARCHAR(MAX) NULL, rutapapeles NVARCHAR(MAX) NULL, rutadoc NVARCHAR(MAX) NULL, observaciones NVARCHAR(MAX) NULL, preparo_fecha DATE NULL, reviso_fecha NVARCHAR(MAX) NULL, revisogte_fecha NVARCHAR(MAX) NULL, revisosocio_fecha NVARCHAR(MAX) NULL, fecha_modif NVARCHAR(MAX) NULL, hora_modif NVARCHAR(MAX) NULL, estado INT NULL, mailasociado NVARCHAR(MAX) NULL, generico NVARCHAR(MAX) NULL, revisoengagement NVARCHAR(MAX) NULL, nivel_doc INT NULL, manejador NVARCHAR(MAX) NULL, fecha_limite NVARCHAR(MAX) NULL, lugar_firma NVARCHAR(MAX) NULL, manejador_final NVARCHAR(MAX) NULL, revisoengagement_fecha NVARCHAR(MAX) NULL, Fecha DATE NULL, fecha_cierre DATE NULL, adjuntos NVARCHAR(MAX) NULL, archivo_temp NVARCHAR(MAX) NULL, archivo_hash NVARCHAR(MAX) NULL, ClienteName NVARCHAR(MAX) NULL ); INSERT INTO #r EXEC dbo.sp_get_hojas_by_nivel_base @Nivel = @Nivel, @Sector = @Sector, @Sectores = @Sectores, @Usuario = @Usuario, @Id = @Id, @Pendientes = @Pendientes; SELECT ISNULL(id, '') AS id, ISNULL(usuario, '') AS usuario, ISNULL(equipo, '') AS equipo, cliente, ISNULL(sector, '') AS sector, ISNULL(subarea, '') AS subarea, ISNULL(numeracion, '') AS numeracion, ISNULL(descripcion, '') AS descripcion, ISNULL(socio_firmante, '') AS socio_firmante, ISNULL(sindica, '') AS sindica, ISNULL(contrato, '') AS contrato, ISNULL(preparo, '') AS preparo, ISNULL(reviso, '') AS reviso, ISNULL(revisogte, '') AS revisogte, ISNULL(revisosocio, '') AS revisosocio, ISNULL(rutapapeles, '') AS rutapapeles, ISNULL(rutadoc, '') AS
rutadoc, ISNULL(observaciones, '') AS observaciones, preparo_fecha, ISNULL(reviso_fecha, '') AS reviso_fecha, ISNULL(revisogte_fecha, '') AS revisogte_fecha, ISNULL(revisosocio_fecha, '') AS revisosocio_fecha, ISNULL(fecha_modif, '') AS fecha_modif, ISNULL(hora_modif, '') AS hora_modif, estado, ISNULL(mailasociado, '') AS mailasociado, ISNULL(generico, '') AS generico, ISNULL(revisoengagement, '') AS revisoengagement, nivel_doc, ISNULL(manejador, '') AS manejador, ISNULL(fecha_limite, '') AS fecha_limite, ISNULL(lugar_firma, '') AS lugar_firma, ISNULL(manejador_final, '') AS manejador_final, ISNULL(revisoengagement_fecha, '') AS revisoengagement_fecha, Fecha, fecha_cierre, ISNULL(adjuntos, '') AS adjuntos, ISNULL(archivo_temp, '') AS archivo_temp, ISNULL(archivo_hash, '') AS archivo_hash, ISNULL(ClienteName, '') AS ClienteName FROM #r; END
GO

-- SP sp_get_hojas_by_nivel_base.sql
CREATE OR ALTER PROCEDURE dbo.sp_get_hojas_by_nivel_base @Nivel INT = NULL, @Sector NVARCHAR(50) = NULL, @Sectores NVARCHAR(MAX) = NULL, @Usuario NVARCHAR(50) = NULL, @Id NVARCHAR(50) = NULL, @Pendientes BIT AS BEGIN SET NOCOUNT ON; IF @Id IS NOT NULL BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE h.id = @Id; RETURN; END; IF @Pendientes = 1 BEGIN IF @Nivel = 11 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE EXISTS ( SELECT 1 FROM Hoja_Estado he WHERE he.HojaId = h.id AND he.Estado = 0 ); RETURN; END; IF @Nivel = 10 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement,
h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE ( ( h.sector = @Sector OR EXISTS ( SELECT 1 FROM STRING_SPLIT(ISNULL(@Sectores, N''), N',') AS sectores WHERE LTRIM(RTRIM(sectores.value)) = h.sector ) ) OR @Usuario IN ( h.preparo, h.reviso, h.revisogte, h.revisosocio, h.revisoengagement, h.manejador, h.manejador_final ) ) AND EXISTS ( SELECT 1 FROM Hoja_Estado he WHERE he.HojaId = h.id AND he.Estado = 0 ); RETURN; END; IF @Nivel <= 9 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE @Usuario IN ( h.preparo, h.reviso, h.revisogte, h.revisosocio, h.revisoengagement, h.manejador, h.manejador_final ) AND EXISTS ( SELECT 1 FROM Hoja_Estado he WHERE he.HojaId = h.id AND he.Revisor = @Usuario AND he.Estado = 0 ); RETURN; END; RETURN; END; IF @Nivel = 11 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp,
h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente; END ELSE IF @Nivel = 10 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE ( h.sector = @Sector OR EXISTS ( SELECT 1 FROM STRING_SPLIT(ISNULL(@Sectores, N''), N',') AS sectores WHERE LTRIM(RTRIM(sectores.value)) = h.sector ) ) OR @Usuario IN ( h.preparo, h.reviso, h.revisogte, h.revisosocio, h.revisoengagement, h.manejador, h.manejador_final ); END ELSE IF @Nivel <= 9 BEGIN SELECT h.id, h.usuario, h.equipo, h.cliente, h.sector, h.subarea, h.numeracion, h.descripcion, h.socio_firmante, h.sindica, h.contrato, h.preparo, h.reviso, h.revisogte, h.revisosocio, h.rutapapeles, h.rutadoc, h.observaciones, h.preparo_fecha, h.reviso_fecha, h.revisogte_fecha, h.revisosocio_fecha, h.fecha_modif, h.hora_modif, h.estado, h.mailasociado, h.generico, h.revisoengagement, h.nivel_doc, h.manejador, h.fecha_limite, h.lugar_firma, h.manejador_final, h.revisoengagement_fecha, h.Fecha, h.fecha_cierre, h.adjuntos, h.archivo_temp, h.archivo_hash, c.RazonSocial AS ClienteName FROM HOJAS h LEFT JOIN Clientes_Creatio c ON c.ID = h.cliente WHERE @Usuario IN ( h.preparo, h.reviso, h.revisogte, h.revisosocio, h.revisoengagement, h.manejador, h.manejador_final ); END END;
GO

-- SP sp_get_next_hoja_numero.sql
CREATE PROCEDURE dbo.sp_get_next_hoja_numero AS BEGIN SET NOCOUNT ON; DECLARE @NextNumero INT; BEGIN TRAN; BEGIN TRY UPDATE dbo.HojaNumerador WITH (UPDLOCK, HOLDLOCK) SET @NextNumero = UltimoNumero = UltimoNumero + 1 WHERE Nombre = 'HOJAS'; IF @NextNumero IS NULL OR @NextNumero <= 0 BEGIN THROW 50001, 'No se pudo reservar el siguiente numero de hoja.', 1; END COMMIT TRAN; RETURN @NextNumero; END TRY BEGIN CATCH IF @@TRANCOUNT > 0 ROLLBACK TRAN; THROW; END CATCH END;
GO

-- SP sp_get_revisores_by_nivel.sql
CREATE OR ALTER PROCEDURE [dbo].[sp_get_revisores_by_nivel] @NivelActual INT = NULL AS BEGIN SELECT * FROM REVISORES WHERE cargo > @NivelActual ORDER BY detalle; END;
GO

-- SP sp_get_hojas_for_reporte.sql
CREATE OR ALTER PROCEDURE [dbo].[sp_get_hojas_for_reporte] @SocioFirmante NVARCHAR(100) = NULL, @FechaDesde DATE = NULL, @FechaHasta DATE = NULL, @ColumnasSeleccionadas NVARCHAR(MAX) = NULL, @Auditoria BIT = 0 AS BEGIN SET NOCOUNT ON; DECLARE @SQL NVARCHAR(MAX); DECLARE @ColumnasIniciales NVARCHAR(MAX); DECLARE @ColumnasAuditoria NVARCHAR(MAX) = N''; DECLARE @JoinAuditoria NVARCHAR(MAX) = N''; DECLARE @Filtros NVARCHAR(MAX) = N' 1=1 '; IF ISNULL(NULLIF(LTRIM(RTRIM(@ColumnasSeleccionadas)), ''), '') <> '' BEGIN SET @ColumnasIniciales = LTRIM(RTRIM(@ColumnasSeleccionadas)); END ELSE BEGIN SET @ColumnasIniciales = N'H.*'; END IF @Auditoria = 1 BEGIN DECLARE @FactorMonedaSQL NVARCHAR(MAX) = N' CASE WHEN A.TipoNumeracion = ''MILES'' THEN 1000.0 WHEN A.TipoNumeracion = ''MILLONES'' THEN 1000000.0 ELSE 1.0 END'; SET @ColumnasAuditoria = N', (A.Activo * ' + @FactorMonedaSQL + N') as Activo, (A.Pasivo * ' + @FactorMonedaSQL + N') as Pasivo, (A.PatrimonioNeto * ' + @FactorMonedaSQL + N') as PatrimonioNeto, A.Moneda, A.TipoNumeracion, (A.Resultado * ' + @FactorMonedaSQL + N') as Resultado, (A.TotalIngresos * ' + @FactorMonedaSQL + N') as TotalIngresos, (A.TotalOtrosIngresos * ' + @FactorMonedaSQL + N') as TotalOtrosIngresos '; SET @JoinAuditoria = N' LEFT JOIN Auditorias AS A ON H.Id = A.HojaId '; END
IF @SocioFirmante IS NOT NULL AND LTRIM(RTRIM(@SocioFirmante)) <> '' BEGIN SET @Filtros = @Filtros + N' AND H.revisosocio = @SocioFirmante '; END IF @FechaDesde IS NOT NULL BEGIN SET @Filtros = @Filtros + N' AND H.fecha >= @FechaDesde '; END IF @FechaHasta IS NOT NULL BEGIN SET @Filtros = @Filtros + N' AND H.fecha <= @FechaHasta '; END SET @SQL = N' SELECT ' + @ColumnasIniciales + @ColumnasAuditoria + N' FROM HOJAS AS H ' + @JoinAuditoria + N' WHERE ' + @Filtros + N' ORDER BY H.numeracion DESC;'; EXEC sp_executesql @SQL, N'@SocioFirmante NVARCHAR(100), @FechaDesde DATE, @FechaHasta DATE', @SocioFirmante = @SocioFirmante, @FechaDesde = @FechaDesde, @FechaHasta = @FechaHasta; END
GO

-- SP sp_sync_usuarios_v2.sql
CREATE OR ALTER PROCEDURE [dbo].[sp_sync_usuarios_v2] @username VARCHAR(100), @empleado VARCHAR(50), @email VARCHAR(150), @area VARCHAR(50), @nivel INT AS BEGIN SET NOCOUNT ON; DECLARE @resultado INT = 0; DECLARE @mailLegacy VARCHAR(150); SET @mailLegacy = UPPER( LEFT( ISNULL(@email, ''), CHARINDEX('@', ISNULL(@email, '') + '@') - 1 ) ); IF @nivel IN (9, 10) BEGIN IF EXISTS ( SELECT 1 FROM socios WHERE mail = @mailLegacy ) BEGIN IF EXISTS ( SELECT 1 FROM socios WHERE mail = @mailLegacy AND ( ISNULL(detalle, '') <> ISNULL(@username, '') OR ISNULL(socio, '') <> ISNULL(LEFT(@empleado, 3), '') OR ISNULL(liderDeArea, 0) <> CASE WHEN @nivel = 10 THEN 1 ELSE 0 END ) ) BEGIN UPDATE socios SET detalle = @username, socio = LEFT(@empleado, 3), liderDeArea = CASE WHEN @nivel = 10 THEN 1 ELSE 0 END WHERE mail = @mailLegacy; SET @resultado = 2; END END ELSE BEGIN INSERT INTO socios ( socio, detalle, mail, liderDeArea ) VALUES ( LEFT(@empleado, 3), @username, @mailLegacy, CASE WHEN @nivel = 10 THEN 1 ELSE 0 END ); SET @resultado = 1; END IF EXISTS ( SELECT 1 FROM revisores WHERE empleado = @empleado ) BEGIN IF EXISTS ( SELECT 1 FROM revisores WHERE empleado = @empleado AND ( ISNULL(detalle, '') <> ISNULL(@username, '') OR ISNULL(mail, '') <> ISNULL(@mailLegacy, '') OR ISNULL(cargo, -1) <> ISNULL(@nivel, -1) OR ISNULL(area, '') <> ISNULL(@area, '') ) ) BEGIN UPDATE revisores SET detalle = @username, mail = @mailLegacy, cargo = @nivel, area = @area WHERE empleado = @empleado; SET @resultado = 2; END END ELSE BEGIN INSERT INTO revisores ( empleado, detalle, mail, cargo, area, subarea ) VALUES ( @empleado, @username, @mailLegacy, @nivel, @area, NULL ); SET @resultado = 1; END RETURN @resultado; END DELETE FROM socios WHERE mail = @mailLegacy; IF EXISTS ( SELECT 1 FROM revisores WHERE empleado = @empleado ) BEGIN IF EXISTS ( SELECT 1 FROM revisores WHERE empleado = @empleado AND ( ISNULL(detalle, '') <> ISNULL(@username, '') OR ISNULL(mail, '') <> ISNULL(@mailLegacy, '') OR ISNULL(cargo, -1) <> ISNULL(@nivel, -1) OR ISNULL(area, '') <> ISNULL(@area, '') ) ) BEGIN UPDATE revisores SET detalle = @username, mail = @mailLegacy, cargo = @nivel,
area = @area WHERE empleado = @empleado; SET @resultado = 2; END END ELSE BEGIN INSERT INTO revisores ( empleado, detalle, mail, cargo, area, subarea ) VALUES ( @empleado, @username, @mailLegacy, @nivel, @area, NULL ); SET @resultado = 1; END RETURN @resultado; END
GO

-- SP sp_sync_usuario_directorio.sql
CREATE OR ALTER PROCEDURE dbo.sp_sync_usuario_directorio @entra_object_id NVARCHAR(100), @mail NVARCHAR(150), @given_name NVARCHAR(150) = NULL, @surname NVARCHAR(150) = NULL, @area NVARCHAR(150) = NULL, @nivel INT = NULL, @detalle NVARCHAR(350) = NULL, @es_hdr BIT, @permitir_reasignacion_por_mail BIT = 0, @resultado_detalle NVARCHAR(500) OUTPUT AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; DECLARE @cambios INT = 0; DECLARE @afectados INT; DECLARE @acciones NVARCHAR(500) = N''; DECLARE @estaba_inactivo BIT; SET @resultado_detalle = N''; BEGIN TRANSACTION; BEGIN TRY IF @es_hdr = 1 AND @permitir_reasignacion_por_mail = 0 AND EXISTS (SELECT 1 FROM dbo.REVISORES WHERE mail = @mail AND NULLIF(entra_object_id, '') IS NOT NULL AND entra_object_id <> @entra_object_id) BEGIN ROLLBACK TRANSACTION; SET @resultado_detalle = N'Conflicto de identidad en REVISORES'; RETURN -3; END IF @es_hdr = 1 AND @permitir_reasignacion_por_mail = 0 AND EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE mail = @mail AND NULLIF(entra_object_id, '') IS NOT NULL AND entra_object_id <> @entra_object_id) BEGIN ROLLBACK TRANSACTION; SET @resultado_detalle = N'Conflicto de identidad en SOCIOS'; RETURN -3; END IF @es_hdr = 0 BEGIN UPDATE dbo.REVISORES SET Hdr_Activo = 0 WHERE Hdr_Activo = 1 AND (entra_object_id = @entra_object_id OR (NULLIF(entra_object_id, '') IS NULL AND mail = @mail)); SET @afectados = @@ROWCOUNT; SET @cambios += @afectados; IF @afectados > 0 SET @acciones += N'RevisorInactivadoPorNoPertenecerGrupoHDR;'; UPDATE dbo.SOCIOS SET Hdr_Activo = 0 WHERE Hdr_Activo = 1 AND (entra_object_id = @entra_object_id OR (NULLIF(entra_object_id, '') IS NULL AND mail = @mail)); SET @afectados = @@ROWCOUNT; SET @cambios += @afectados; IF @afectados > 0 SET @acciones += N'SocioInactivadoPorNoPertenecerGrupoHDR;'; COMMIT TRANSACTION; SET @resultado_detalle = @acciones; RETURN @cambios; END DECLARE @subarea NVARCHAR(150); SELECT TOP (1) @subarea = r.subarea FROM dbo.REVISORES r WHERE (r.entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND r.mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(r.entra_object_id, '') IS NULL AND
r.mail = @mail)) AND EXISTS (SELECT 1 FROM dbo.SUBAREA sa WHERE sa.subarea = r.subarea AND sa.sector = @area) ORDER BY r.subarea; IF @subarea IS NULL BEGIN SELECT TOP (1) @subarea = sa.subarea FROM dbo.SUBAREA sa WHERE sa.sector = @area ORDER BY sa.subarea; END IF EXISTS (SELECT 1 FROM dbo.REVISORES WHERE entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail)) BEGIN SET @estaba_inactivo = CASE WHEN EXISTS (SELECT 1 FROM dbo.REVISORES WHERE Hdr_Activo = 0 AND (entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail))) THEN 1 ELSE 0 END; UPDATE dbo.REVISORES SET empleado = @mail, mail = @mail, detalle = @detalle, cargo = @nivel, area = @area, subarea = @subarea, entra_object_id = @entra_object_id, Hdr_Activo = 1 WHERE (entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail)) AND (ISNULL(empleado, '') <> @mail OR ISNULL(detalle, '') <> @detalle OR ISNULL(cargo, -1) <> @nivel OR ISNULL(area, '') <> @area OR ISNULL(subarea, '') <> ISNULL(@subarea, '') OR ISNULL(entra_object_id, '') <> @entra_object_id OR Hdr_Activo <> 1); SET @afectados = @@ROWCOUNT; SET @cambios += @afectados; IF @afectados > 0 SET @acciones += CASE WHEN @estaba_inactivo = 1 THEN N'RevisorReactivado;' ELSE N'RevisorActualizado;' END; END ELSE BEGIN INSERT INTO dbo.REVISORES (empleado, detalle, mail, cargo, area, subarea, entra_object_id, Hdr_Activo) VALUES (@mail, @detalle, @mail, @nivel, @area, @subarea, @entra_object_id, 1); SET @cambios += 1; SET @acciones += N'RevisorCreado;'; END IF @nivel NOT IN (9, 10) BEGIN UPDATE dbo.SOCIOS SET Hdr_Activo = 0 WHERE Hdr_Activo = 1 AND (entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND
mail = @mail)); SET @afectados = @@ROWCOUNT; SET @cambios += @afectados; IF @afectados > 0 SET @acciones += N'SocioInactivadoPorCambioDeNivel;'; COMMIT TRANSACTION; SET @resultado_detalle = @acciones; RETURN @cambios; END IF EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail)) BEGIN SET @estaba_inactivo = CASE WHEN EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE Hdr_Activo = 0 AND (entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail))) THEN 1 ELSE 0 END; UPDATE dbo.SOCIOS SET mail = @mail, detalle = @detalle, liderDeArea = CASE WHEN @nivel = 10 THEN 1 ELSE 0 END, entra_object_id = @entra_object_id, Hdr_Activo = 1 WHERE (entra_object_id = @entra_object_id OR (@permitir_reasignacion_por_mail = 1 AND mail = @mail) OR (@permitir_reasignacion_por_mail = 0 AND NULLIF(entra_object_id, '') IS NULL AND mail = @mail)) AND (ISNULL(mail, '') <> @mail OR ISNULL(detalle, '') <> @detalle OR ISNULL(liderDeArea, 0) <> CASE WHEN @nivel = 10 THEN 1 ELSE 0 END OR ISNULL(entra_object_id, '') <> @entra_object_id OR Hdr_Activo <> 1); SET @afectados = @@ROWCOUNT; SET @cambios += @afectados; IF @afectados > 0 SET @acciones += CASE WHEN @estaba_inactivo = 1 THEN N'SocioReactivado;' ELSE N'SocioActualizado;' END; END ELSE BEGIN DECLARE @codigo NVARCHAR(50) = UPPER(LEFT(@surname, 1) + LEFT(@given_name, 1)); IF EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE socio = @codigo) SET @codigo = UPPER(LEFT(@given_name, 1) + LEFT(@surname, 1)); IF EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE socio = @codigo) SET @codigo = UPPER(LEFT(@surname, 2)); IF EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE socio = @codigo) SET @codigo = UPPER(LEFT(@given_name, 2)); DECLARE @baseCodigo NVARCHAR(50) = @codigo; DECLARE @sufijo INT = 2; WHILE EXISTS (SELECT 1 FROM dbo.SOCIOS WHERE socio = @codigo) BEGIN SET @codigo = @baseCodigo + CONVERT(NVARCHAR(10), @sufijo); SET @sufijo += 1; END
INSERT INTO dbo.SOCIOS (socio, detalle, mail, sector, liderDeArea, entra_object_id, Hdr_Activo) VALUES (@codigo, @detalle, @mail, @area, CASE WHEN @nivel = 10 THEN 1 ELSE 0 END, @entra_object_id, 1); SET @cambios += 1; SET @acciones += N'SocioCreado;'; END COMMIT TRANSACTION; SET @resultado_detalle = @acciones; RETURN @cambios; END TRY BEGIN CATCH IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION; THROW; END CATCH END
GO

-- SP sp_inactivar_usuarios_directorio_ausentes.sql
CREATE OR ALTER PROCEDURE dbo.sp_inactivar_usuarios_directorio_ausentes @usuarios_directorio dbo.HDR_DirectoryUserIdentity READONLY AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; DECLARE @cambios INT = 0; BEGIN TRANSACTION; BEGIN TRY UPDATE r SET Hdr_Activo = 0 FROM dbo.REVISORES r WHERE r.Hdr_Activo = 1 AND NOT EXISTS ( SELECT 1 FROM @usuarios_directorio u WHERE (NULLIF(r.entra_object_id, '') IS NOT NULL AND u.EntraObjectId = r.entra_object_id) OR (NULLIF(r.entra_object_id, '') IS NULL AND u.Mail IS NOT NULL AND u.Mail = r.mail) ); SET @cambios += @@ROWCOUNT; UPDATE s SET Hdr_Activo = 0 FROM dbo.SOCIOS s WHERE s.Hdr_Activo = 1 AND NOT EXISTS ( SELECT 1 FROM @usuarios_directorio u WHERE (NULLIF(s.entra_object_id, '') IS NOT NULL AND u.EntraObjectId = s.entra_object_id) OR (NULLIF(s.entra_object_id, '') IS NULL AND u.Mail IS NOT NULL AND u.Mail = s.mail) ); SET @cambios += @@ROWCOUNT; COMMIT TRANSACTION; RETURN @cambios; END TRY BEGIN CATCH IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION; THROW; END CATCH END
GO

-- SP sp_inactivar_usuarios_directorio_sin_hdr.sql
CREATE OR ALTER PROCEDURE dbo.sp_inactivar_usuarios_directorio_sin_hdr @usuarios_hdr dbo.HDR_DirectoryReconciliationIdentity READONLY AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; DECLARE @cambios INT = 0; BEGIN TRANSACTION; BEGIN TRY UPDATE r SET Hdr_Activo = 0 FROM dbo.REVISORES r WHERE r.Hdr_Activo = 1 AND NOT EXISTS (SELECT 1 FROM @usuarios_hdr u WHERE u.EntraObjectId = r.entra_object_id OR (NULLIF(r.entra_object_id, '') IS NULL AND u.AllowMailFallback = 1 AND u.Mail = r.mail)); SET @cambios += @@ROWCOUNT; UPDATE s SET Hdr_Activo = 0 FROM dbo.SOCIOS s WHERE s.Hdr_Activo = 1 AND NOT EXISTS (SELECT 1 FROM @usuarios_hdr u WHERE u.EntraObjectId = s.entra_object_id OR (NULLIF(s.entra_object_id, '') IS NULL AND u.AllowMailFallback = 1 AND u.Mail = s.mail)); SET @cambios += @@ROWCOUNT; COMMIT TRANSACTION; RETURN @cambios; END TRY BEGIN CATCH IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION; THROW; END CATCH END
GO

-- SP sp_get_socio_lider_by_area.sql
CREATE OR ALTER PROCEDURE [dbo].[sp_get_socio_lider_by_area] @Area NVARCHAR(50) = NULL AS BEGIN SELECT s.* FROM socios s WHERE s.sector = @Area AND s.liderDeArea = 1 AND s.Hdr_Activo = 1; END;
GO

-- COMPROBACIONES DE LOS SP
EXEC dbo.sp_get_hojas_index_paged @Nivel = 0, @Sector = N'', @Sectores = NULL, @Usuario = N'__smoke_test__', @Pendientes = 0, @Numero = NULL, @Cliente = NULL, @Estado = NULL, @SectorFiltro = NULL, @Socio = NULL, @FechaDesde = NULL, @FechaHasta = NULL, @SortField = N'Numero', @SortDirection = N'asc', @PageNumber = 1, @PageSize = 1;
EXEC dbo.sp_get_hojas_by_nivel @Nivel = 0, @Sector = N'', @Sectores = NULL, @Usuario = N'__smoke_test__', @Id = NULL, @Pendientes = 0;
EXEC dbo.sp_get_hojas_by_nivel_base @Nivel = 0, @Sector = N'', @Sectores = NULL, @Usuario = N'__smoke_test__', @Id = NULL, @Pendientes = 0;